const fs = require("fs");
const os = require("os");
const path = require("path");

const PROJECT_ROOT = path.resolve(__dirname, "..");
const ENV_LOCAL_PATH = path.join(PROJECT_ROOT, ".env.local");
const DEFAULT_PORT = process.env.EXPO_PUBLIC_API_PORT || "4000";
const DEFAULT_SCHEME = process.env.EXPO_PUBLIC_API_SCHEME || "http";

function isPrivateIpv4(address) {
  return (
    /^10\./.test(address) ||
    /^192\.168\./.test(address) ||
    /^172\.(1[6-9]|2\d|3[0-1])\./.test(address)
  );
}

function scoreCandidate(name, address) {
  const normalized = name.toLowerCase();
  let score = 0;

  if (!isPrivateIpv4(address)) {
    score -= 1000;
  }

  if (/wi-?fi|wlan|wireless/.test(normalized)) {
    score += 120;
  }

  if (/ethernet|en\d|eth\d/.test(normalized)) {
    score += 80;
  }

  if (/virtual|vbox|vmware|hyper-v|tailscale|hamachi|loopback|bluetooth|docker|wsl/.test(normalized)) {
    score -= 400;
  }

  if (/^192\.168\./.test(address)) {
    score += 40;
  } else if (/^10\./.test(address)) {
    score += 30;
  } else if (/^172\./.test(address)) {
    score += 20;
  }

  return score;
}

function findBestLanAddress() {
  const interfaces = os.networkInterfaces();
  const candidates = [];

  for (const [name, addresses] of Object.entries(interfaces)) {
    for (const entry of addresses ?? []) {
      if (
        entry.family !== "IPv4" ||
        entry.internal ||
        !entry.address ||
        !isPrivateIpv4(entry.address)
      ) {
        continue;
      }

      candidates.push({
        name,
        address: entry.address,
        score: scoreCandidate(name, entry.address),
      });
    }
  }

  candidates.sort((left, right) => right.score - left.score);
  return candidates[0] ?? null;
}

function writeEnvLocal(host) {
  const lines = [
    "# Auto-generated by scripts/configure-lan.js",
    `EXPO_PUBLIC_API_HOST=${host}`,
    `EXPO_PUBLIC_API_PORT=${DEFAULT_PORT}`,
    `EXPO_PUBLIC_API_SCHEME=${DEFAULT_SCHEME}`,
    "",
  ];

  fs.writeFileSync(ENV_LOCAL_PATH, lines.join("\n"), "utf8");
}

function main() {
  const candidate = findBestLanAddress();

  if (!candidate) {
    console.error(
      "Unable to detect a private LAN IPv4 address. Connect to Wi-Fi/LAN or set EXPO_PUBLIC_API_HOST manually.",
    );
    process.exit(1);
  }

  writeEnvLocal(candidate.address);

  console.log(
    `Configured Expo API host to ${candidate.address}:${DEFAULT_PORT} from interface "${candidate.name}".`,
  );
  console.log(`Wrote ${path.relative(PROJECT_ROOT, ENV_LOCAL_PATH)}.`);
}

main();
